obj-y			+= am-cam-device.o
obj-y			+= am-cam-video.o
obj-y			+= am-cam-debug.o
obj-y			+= am-cam-framemgr.o
obj-y			+= hw/fimc_is_hw_regs.o
obj-y			+= hw/fimc-is-csi.o
obj-y			+= i2c/ISP_I2C_Driver.o
obj-y			+= i2c/i2c_api.o
obj-y			+= sensor/sensor_module.o
obj-y			+= sensor/s5k4ec_soc.o
obj-y			+= setup-fimc-is.o
obj-y			+= setup-fimc-is-sensor.o

KBUILD_CFLAGS   += -Werror

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/am-cam -Idrivers/media/platform/exynos/am-cam/include
