obj-$(CONFIG_DRM_PANEL) = panel-drv.o
obj-$(CONFIG_DRM_PANEL_SIMPLE) += panel-simple.o
obj-$(CONFIG_DRM_PANEL_LD9040) += panel-ld9040.o
obj-$(CONFIG_DRM_PANEL_S6E8AA0) += panel-s6e8aa0.o
obj-$(CONFIG_DRM_PANEL_S6E3HA2K) += panel-s6e3ha2k.o
obj-$(CONFIG_DRM_PANEL_AMSA20JW01) += panel-amsa20jw01.o
