# Linux 2.6 Kernel Makefile
# New format.  All building is done within the kernel development
# tree.  The user's makefile no longer needs to specify all build rules
# and kernel defines.  Its all done by the kernel now.
#
# For full details on bulding a kernel module see:
# 
# To build with more verbose output run:
# 	$> make V=1 

# obj-$(CONFIG_EXYNOS_ADI_IF_2) += adipcie.o
